name: Deploy HINDP to ECS

on:
  push:
    branches: [ main ]

env:
  ECS_CLUSTER: asnsub-api-ecs
  ECS_SERVICE: asnsub-api-hindp-v2
  ECR_REPOSITORY: asnsub-hindp

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        run: |
          docker build -t ${ECR_REPOSITORY}:latest .
          docker tag ${ECR_REPOSITORY}:latest \
            854878589422.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}:latest
          docker push \
            854878589422.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${ECS_CLUSTER} \
            --service ${ECS_SERVICE} \
            --force-new-deployment
